# Copyright (C) 2025 Rob Hall
# SPDX-License-Identifier: MIT

option('enable_examples',
    type: 'boolean',
    value: false,
    description: 'Build libudfread examples')

option('enable_docs',
    type: 'boolean',
    value: false,
    description: 'Build doxygen documentation')

option('enable_tests',
    type: 'boolean',
    value: false,
    description: 'Build and run libudfread unit and API tests')

option('embed_udfread',
    type: 'boolean',
    value: false,
    yield: true,
    description: 'Build libudfread as static library with no install')
